---
title: "ZrnDash"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    vertical_layout: scroll
---

```{r setup, include=FALSE}
# RMarkdown zircon geochronology dashboard template updated 2018.08.22 CH.

# install missing packages, load packages
  # knitr for assembling RMarkdown documents
  if(!require(knitr)){install.packages("knitr")}  # install
  library(knitr)  # load
  # ggplot for making graphs
  if(!require(ggplot2)){install.packages("ggplot2", dependencies = TRUE)}
  library(ggplot2)  # load
  # plyr for combining data frames, displaying dashboard
  if(!require(plyr)){install.packages("plyr")}  # install
  library(plyr)  # load
  # dplyr for making plotly work
  if(!require(dplyr)){install.packages("dplyr", dependencies = TRUE)} 
  library(dplyr)  # load
  # plotly for making interactive graphs
  if(!require(plotly)){install.packages("plotly", dependencies = TRUE)} 
  library(plotly)  # load
  # flexdashboard for making dashboards
  if(!require(flexdashboard)){install.packages("flexdashboard")}  # install
  library(flexdashboard)  # load
  # RColorBrewer package for color palette
  if(!require(RColorBrewer)){install.packages("RColorBrewer")}  # install
  library(RColorBrewer)  # load
  # reshape2 for melting data frames
  if(!require(reshape2)){install.packages("reshape2")}  # install
  library(reshape2)  # load
  # leaflet extracts color codes from a palette given a value (for REE plots)
  if(!require(leaflet)){install.packages("leaflet")}  # install
  library(leaflet)  # load
  # ggfortify for plotting output of MDS
  if(!require(ggfortify)){install.packages("ggfortify")}  # install
  library(ggfortify)  # load
  # BBmisc for normalizing data frame function
  if(!require(BBmisc)){install.packages("BBmisc")}  # install
  library(BBmisc)  # load
  # The pcaMethods package allows you to do PCA on datasets with missing (NA) or
  # outlier data. 
  # https://bioconductor.org/packages/release/bioc/html/pcaMethods.html
  if(!require(pcaMethods)){source("https://bioconductor.org/biocLite.R")
  biocLite("pcaMethods")}  # install
  library(pcaMethods)  # load


# clear all from workspace/environment
  rm(list=ls())

# Set universal settings. 
  # For all code chunks, omit code in knited document and hide messages and 
  # warnings.
  knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE) 

  # Set working directory.
  knitr::opts_knit$set(root.dir = 
  "/Users/claireharrigan/Dropbox/IGL + Research/R/graphit/")
```

```{r import, include=FALSE}
# functions required:
  source("ImportZirconFDT.R") # for importing and cleaning up files
  source("SplitAnalysis.R") # for cleaning up LA-ICPMS analysis strings 
  
# Import zircon LA-ICPMS data.
  # First, save your final data table as a .csv file with the values as numbers
  # with many decimal places.
  # Type file.choose() in the console, then hit enter to select the file. Copy
  # and paste the resulting filepath into the function below.
  ImportedDF <- ImportZirconFDT("17RF7-2 zrn_FDT.csv")
  # Save a data frame of LA-ICPMS samples only (no standards).
  DF <- ImportedDF[[1]]
  # Apply the SplitAnalysis function to the analysis column and save the results
  # as a temporary dataframe.
  tempDF <- SplitAnalysis(column.name = DF$analysis) 
  # Save sample name from temporary dataframe into the main dataframe.
  DF$sample <- tempDF$samp.name
  # Save mount size from temporary dataframe into the main dataframe.
  DF$size <- tempDF$size 
  # Save spot number from temporary datafrae into the main dataframe.
  DF$spot <- tempDF$spot 
  # OPTIONALL Remove spots that are not zircon (uncomment next line and edit).
  #DF <- subset(DF, spot != 135)
  rm(tempDF)  # remove temporary data frame from environment

# OPTIONAL: Import a second zircon LA-ICPMS final data table 
# Uncomment this section and edit filepath of the next line to import a second
# final data table.
  # ImportedDF2 <- Import("/Users/claireharrigan/Dropbox/IGL + Research/WISZ/Results/14WZ3-2 LGCC Gpg/zircon/Geochemistry/zircon_14WZ3-2_LA-ICPMS FDT.csv")
  # # Save a data frame of LA-ICPMS samples only (no standards).
  # DF2 <- ImportedDF2[[1]]
  # # Apply the SplitAnalysis function to the analysis column and save the results
  # # as a temporary dataframe.
  # tempDF2 <- SplitAnalysis(column.name = DF2$analysis) 
  # # Save sample name from temporary dataframe into the main dataframe.
  # DF2$sample <- tempDF2$samp.name
  # # Save mount size from temporary dataframe into the main dataframe.
  # DF2$size <- tempDF2$size 
  # # Save spot number from temporary datafrae into the main dataframe.
  # DF2$spot <- tempDF2$spot 
  # # Remove spots that are not zircon (optional--uncomment next line and edit).
  # #DF2 <- subset(DF2, spot != 135)
  # rm(tempDF2)  # remove temporary data frame from environment

# OPTIONAL: Bind all imported data frames together and remove extra data frames.
# Uncomment the following section if importing multiple final data tables.
  # DF <- rbind.fill(DF, DF2)  # Combine using rbind.fill function from plyr.
  # rm(DF2)  # Remove individual sample data frames.
```

```{r set_values, include=FALSE}
# Set values for Ti-in-zircon thermometer.
  aTiO2 = 0.7     # set activity of TiO2
  aSiO2 = 1       # set activity of SiO2

# Set text to describe samples.
sample.notes = "This is the template for creating a zircon geochemistry dashboard with LA-ICPMS data."
```

```{r calculate, include=FALSE}
# functions required for calculations and plotting:
  source("ChondriteNormalization.R")  # for normalizing REE values
  source("CalculateRatios.R")  # for calculating trace element ratios
  source("PlotlyBivariateZrn.R")  # for making interactive bivariate plots
  source("PlotlySummedPDFZrn.R")  # for making interactive summed PDF
  source("PlotlyREE.R")  # for making interactive REE plots

# Create new columns based on sample, size, and spot information.
  # Create "size spot" column for unique naming for PCA and MDS (ex. "M 132").
  DF$size.spot <- paste(DF$size, " ", DF$spot, sep="") # create 
  # Create "sample size spot" column for unique naming for PCA and MDS.
  DF$sample.size.spot <- paste(DF$sample, " ", DF$size, " ", DF$spot, sep="")

# Create chondrite normalized REE values for plotting REE patterns.
  DF <- ChondriteNormalization(DF)

# Calculate temperature in °C using Ferry and Watson (2007) Ti-in-zircon 
# thermometer and save as a column in data frame.
  DF$temperature <- (-4800 / (log10(DF$Ti) - 5.711 + log10(aSiO2) - 
                     log10(aTiO2))) - 273.15

# Sort the data frame by decreasing temperature.
  DF <- DF[order(DF$temperature, decreasing = TRUE), ] 

# Calculate trace element and REE ratios. Round temperature.
  DF <- CalculateRatios(DF)
  
# Make a new column in the data frame of your preferred age and error.
  DF$Age <- DF$Age_CalibError_206Pb238U
  DF$Age2sig <- DF$Age_CalibError_206Pb238U_2sig
  # Round these columns (save as new column) to one decimal place (useful for
  # labeling).
  DF$Age_round <- round(DF$Age, digits = 1)
  DF$Age2sig_round <- round(DF$Age2sig, digits = 1)
```

Bivariate plots
================================================================================
`r sample.notes`

Row
--------------------------------------------------------------------------------

### Probability Density Function (PDF) of LA-ICPMS Age
```{r page1_1}
PlotlySummedPDFZrn(DF)
```

### Age vs. Total REE
```{r page1_2}
PlotlyBivariateZrn(dataframe = DF,  
                   x.value   = Age, 
                   x.name    = "Age (Ma)", 
                   y.value   = sumREE, 
                   y.name    = "Total REE (ppm)")
```

Row
--------------------------------------------------------------------------------

### Eu anomaly vs. Total REE
```{r page1_3}
PlotlyBivariateZrn(dataframe = DF,  
                   x.value   = EuEustar, 
                   x.name    = "Eu/Eu*", 
                   y.value   = sumREE, 
                   y.name    = "Total REE (ppm)")
```

### Dy anomaly vs. Total REE
```{r page1_4}
PlotlyBivariateZrn(dataframe = DF,  
                   x.value   = DyDystar, 
                   x.name    = "Dy/Dy*", 
                   y.value   = sumREE, 
                   y.name    = "Total REE (ppm)")
```

Row
--------------------------------------------------------------------------------

### U vs. Total REE
```{r page1_5}
PlotlyBivariateZrn(dataframe = DF,  
                   x.value   = U, 
                   x.name    = "U (ppm)", 
                   y.value   = sumREE, 
                   y.name    = "Total REE (ppm)")
```

### Th/U vs. Total REE
```{r page1_6}
PlotlyBivariateZrn(dataframe = DF,  
                   x.value   = ThU, 
                   x.name    = "Th/U", 
                   y.value   = sumREE, 
                   y.name    = "Total REE (ppm)")
```

Row
--------------------------------------------------------------------------------

### Lu/Hf vs. Total REE
```{r page1_7}
PlotlyBivariateZrn(dataframe = DF,  
                   x.value   = LuHf, 
                   x.name    = "Lu/Hf", 
                   y.value   = sumREE, 
                   y.name    = "Total REE (ppm)")
```

### Zr/Hf vs. Total REE
```{r page1_8}
PlotlyBivariateZrn(dataframe = DF,  
                   x.value   = ZrHf, 
                   x.name    = "Zr/Hf", 
                   y.value   = sumREE, 
                   y.name    = "Total REE (ppm)")
```

Row
--------------------------------------------------------------------------------

### Nb/Th vs. Total REE
```{r page1_9}
PlotlyBivariateZrn(dataframe = DF,  
                   x.value   = NbTh, 
                   x.name    = "Nb/Th", 
                   y.value   = sumREE, 
                   y.name    = "Total REE (ppm)")
```

### Nb/Ta vs. Total REE
```{r page1_10}
PlotlyBivariateZrn(dataframe = DF,  
                   x.value   = NbTa, 
                   x.name    = "Nb/Ta", 
                   y.value   = sumREE, 
                   y.name    = "Total REE (ppm)")
```


REE plots
================================================================================
`r sample.notes`  
REE plots are colored by the same temperature scale used for the bivariate plots.

Row
--------------------------------------------------------------------------------
```{r REE_setup, include = FALSE}
# Resort the data frame by increasing temperature.
  DF.REE <- DF[order(DF$temperature, decreasing = FALSE), ] 
```

### REE plot 1
```{r page2_1}
PlotlyREE(dataframe    = DF.REE,
          start.sample = DF.REE[[(dim(DF.REE)[1] / 4 * 3 + 1), 
                                 "sample.size.spot"]],
          end.sample   = DF.REE[[(dim(DF.REE)[1]), "sample.size.spot"]])
```

### REE plot 2
```{r page2_2}
PlotlyREE(dataframe    = DF.REE,
          start.sample = DF.REE[[(dim(DF.REE)[1] / 4 * 2 + 1), 
                                 "sample.size.spot"]],
          end.sample   = DF.REE[[(dim(DF.REE)[1] / 4 * 3), "sample.size.spot"]])
```

Row
--------------------------------------------------------------------------------

### REE plot 3
```{r page2_3}
PlotlyREE(dataframe    = DF.REE,
          start.sample = DF.REE[[(dim(DF.REE)[1] / 4 + 1), "sample.size.spot"]],
          end.sample   = DF.REE[[(dim(DF.REE)[1] / 4 * 2), "sample.size.spot"]])
```

### REE plot 4
```{r page2_4}
PlotlyREE(dataframe    = DF.REE,
          start.sample = DF.REE[[1, "sample.size.spot"]],
          end.sample   = DF.REE[[(dim(DF.REE)[1] / 4), "sample.size.spot"]])
```


Principal component analysis
================================================================================
`r sample.notes`  
This section is in progress.
Need to include notes about parameters used for PCA (scaling, centering, etc.).

Row
-------------------------------------------------------------------------------
### PCA scree plot
```{r PCA_1, echo=FALSE, message=FALSE, warning=FALSE}
# Set up for PCA 
  # Make data frame of variables to be included in MDS/PCA and for labeling.
  DF.PCA <- subset(DF, select = c(sample, sample.size.spot,
                                  Age_round, Age2sig_round, 
                                  Pbstar, Ti, Y, Zr, Nb, Lu, Hf, Ta, 
                                  Th, U, 
                                  La_CN, Ce_CN, Pr_CN, Nd_CN, Pm_CN, 
                                  Sm_CN, Eu_CN, Gd_CN, Tb_CN, Dy_CN, 
                                  Ho_CN, Er_CN, Tm_CN, Yb_CN, Lu_CN, 
                                  temperature_r, sumREE, 
                                  LaNd, GdLu, GdYb, ZrHf, LuHf, HfY, 
                                  YHo, ThU, ThY, NbTa, NbU, NbTh, 
                                  DyYb,
                                  CeCestar, EuEustar, DyDystar)) 

  # Make age and error character strings so they do not get normalized with the 
  # rest of the numeric data in the data frame.
  DF.PCA[["sample"]] <- as.character(DF.PCA[["sample"]])
  DF.PCA[["sample.size.spot"]] <- as.character(DF.PCA[["sample.size.spot"]])
  DF.PCA[["Age_round"]] <- as.character(DF.PCA[["Age_round"]])
  DF.PCA[["Age2sig_round"]] <- as.character(DF.PCA[["Age2sig_round"]])

  # Do principal component analysis.
  # Center the matrix to make the SVD method like doing standard PCA via a
  # covariance matrix. Use pareto scaling. Pull out ten principal components.
  pc.results <- pca(DF.PCA, scale = "uv", center = TRUE, nPcs = 10)
  # pc.test.1 <- pca(DF.PCA, scale = "uv", center = TRUE, nPcs = 10)
  
  # Store the results of the principal component analysis in a data frame for 
  # plotting.
  # Save the variance percent in the data frame.
  PCA.results <- as.data.frame(pc.results@R2)
  # Save the cummulative percent in the data frame.
  PCA.results$cummulative.percent <- pc.results@R2cum
  # Make a column of axis labels.
  PCA.results$axis.labels <- c("PC1", "PC2", "PC3", "PC4", "PC5", "PC6", "PC7", 
                             "PC8", "PC9", "PC10")
  # Make the axis label column into factors so it does not plot alphabetically.
  PCA.results$axis.labels <- factor(PCA.results$axis.labels, levels = c("PC1", 
                             "PC2", "PC3", "PC4", "PC5", "PC6", "PC7", "PC8", 
                             "PC9", "PC10"))
  # Name the data frame rows using the axis labels column.
  rownames(PCA.results) <- PCA.results$axis.labels
  # Rename the columns.
  colnames(PCA.results) <- c("VariancePercent", "CummulativePercent",
                             "PrincipalComponent")
  # Create a column of rounded variance percent for hovertext.
  PCA.results$VariancePercent_round <- round(PCA.results$VariancePercent * 100, 
                                             digits = 1)
  # Create a column of rounded cummulative percent for hovertext.
  PCA.results$CummulativePercent_round <- round(PCA.results$CummulativePercent 
                                                * 100, digits = 1)
```

```{r PCA_2, echo=FALSE, message=FALSE, warning=FALSE}
# Make a scree plot.
  plot_ly(data = PCA.results, 
          x = ~PrincipalComponent, 
          y = ~VariancePercent*100,
          name = "Variance percent",
          type = "bar",
          marker = list(color = "gray",
                        line = list(color = "black",
                                    width = 1)),
          hoverinfo = 'text',
          text = ~paste(PrincipalComponent,
                        "<br>Variance percent: ",
                        VariancePercent_round, "%",
                        "<br>Cummulative percent: ",
                        CummulativePercent_round, "%", 
                        sep = '')) %>%
    add_trace(data = PCA.results, 
              x = ~PrincipalComponent, 
              y = ~VariancePercent*100, 
              type = "scatter", 
              mode = "lines+markers", 
              line = list(color = "black"), 
              marker = list(color = "black")) %>%
    add_trace(data = PCA.results, 
              x = ~PrincipalComponent, 
              y = ~CummulativePercent*100, 
              name = "Cummulative percent",
              type = "scatter", 
              mode = "lines+markers", 
              line = list(color = "red", 
                          dash = "dot"), 
              marker = list(color = "red")) %>%
    layout(xaxis = list(title = "Principal component"), 
           yaxis = list(title = "Percentage of explained variance"),
          bargap = 0)
```

### - 

Row
--------------------------------------------------------------------------------

### PC1 vs. PC2 score plot
```{r PCA_3, echo=FALSE, message=FALSE, warning=FALSE}
# Save PCA score data in new data frame.
  PCA.scores <- as.data.frame(pc.results@scores)
  # Save identifying information to PCA.scores data frame.
  PCA.scores$sample <- DF.PCA$sample
  PCA.scores$sample.size.spot <- DF.PCA$sample.size.spot
  PCA.scores$temperature_r <- DF.PCA$temperature_r
  PCA.scores$Age_round <- DF.PCA$Age_round
  PCA.scores$Age2sig_round <- DF.PCA$Age2sig_round
  
# Make plot of PC1 vs. PC2 scores (PCA by sample).
  plot_ly(data = PCA.scores, 
          x = ~PC1,
          y = ~PC2,
          name = "sample.size.spot",
          type = "scatter", 
          mode = "markers",
          marker = list(size = 12, 
                        line = list(color = "black", 
                                    width = 1)),
          color = ~temperature_r, 
          colors = rev(brewer.pal
                       (n = 11, name = "Spectral")),
          symbol = ~sample,
          symbols = c('circle',
                      'circle',
                      'square',
                      'triangle-up',
                      'diamond'),
          hoverinfo = 'text',
          text = ~paste(sample.size.spot,
                        '<br>LA-ICPMS age: ',
                        Age_round,
                        ' ± ',
                        Age2sig_round,
                        ' Ma<br>Temperature: ',
                        temperature_r, '°C',
                        sep = '')) %>%
    colorbar(title = "Temperature (°C)") %>%
    layout(xaxis = list(title = "PC1 Score"),
           yaxis = list(title = "PC2 Score"))
```

### PC1 vs. PC2 load plot
```{r PCA_4, echo=FALSE, message=FALSE, warning=FALSE}
# Save PCA loading data in new data frame.
  PCA.loadings <- as.data.frame(pc.results@loadings)
  # Save identifying information to PCA.loadings data frame.
  PCA.loadings$variable <- c("Pb*", "Ti", "Y", "Zr", "Nb", "Lu", "Hf", "Ta",
                             "Th", "U",
                             "La (CN)", "Ce (CN)", "Pr (CN)", "Nd (CN)", 
                             "Pm (CN)", "Sm (CN)", "Eu (CN)", "Gd (CN)", 
                             "Tb (CN)", "Dy (CN)", "Ho (CN)", "Er (CN)", 
                             "Tm (CN)", "Yb (CN)", "Lu (CN)",
                             "Temperature (°C)", "Total REE",
                             "La/Nd", "Gd/Lu", "Gd/Yb", "Zr/Hf", "Lu/Hf",
                             "Hf/Y", "Y/Ho", "Th/U", "Th/Y", "Nb/Ta", "Nb/U", 
                             "Nb/Th", "Dy/Yb",
                             "Ce/Ce*", "Eu/Eu*", "Dy/Dy*")

# Make plot of PC1 vs. PC2 loadings (PCA by variable).
  plot_ly(data = PCA.loadings, 
          x = ~PC1,
          y = ~PC2,
          name = "variable",
          type = "scatter", 
          mode = "markers",
          marker = list(size = 12, 
                        line = list(color = "black", 
                                    width = 1)),
          hoverinfo = 'text',
          text = ~paste(variable)) %>%
    layout(xaxis = list(title = "PC1 Load"),
           yaxis = list(title = "PC2 Load"))
```

Row
--------------------------------------------------------------------------------

### PC2 vs. PC3 score plot
```{r PCA_5, echo=FALSE, message=FALSE, warning=FALSE}
# Make plot of PC1 vs. PC2 scores.
  plot_ly(data = PCA.scores, 
          x = ~PC2,
          y = ~PC3,
          name = "sample.size.spot",
          type = "scatter", 
          mode = "markers",
          marker = list(size = 12, 
                        line = list(color = "black", 
                                    width = 1)),
          color = ~temperature_r, 
          colors = rev(brewer.pal
                       (n = 11, name = "Spectral")),
          symbol = ~sample,
          symbols = c('circle',
                      'circle',
                      'square',
                      'triangle-up',
                      'diamond'),
          hoverinfo = 'text',
          text = ~paste(sample.size.spot,
                        '<br>LA-ICPMS age: ',
                        Age_round,
                        ' ± ',
                        Age2sig_round,
                        ' Ma<br>Temperature: ',
                        temperature_r, '°C',
                        sep = '')) %>%
    colorbar(title = "Temperature (°C)") %>%
    layout(xaxis = list(title = "PC2 Score"),
           yaxis = list(title = "PC3 Score"))
```

### PC2 vs. PC3 load plot
```{r PCA_6, echo=FALSE, message=FALSE, warning=FALSE}
# Make plot of PC2 vs. PC3 loadings.
  plot_ly(data = PCA.loadings, 
          x = ~PC2,
          y = ~PC3,
          name = "variable",
          type = "scatter", 
          mode = "markers",
          marker = list(size = 12, 
                        line = list(color = "black", 
                                    width = 1)),
          hoverinfo = 'text',
          text = ~paste(variable)) %>%
    layout(xaxis = list(title = "PC2 Load"),
           yaxis = list(title = "PC3 Load"))
```







